name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: python setup
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: install dependencies
      run: |
        pip3 install -r requirements.txt
        sudo python3 ./webapp/nltk_downloader.py
    - name: run
      run: |
        export FLASK_APP=webapp/app
        flask run & sleep 5
    - name: test
      run: python3 ./tests/test_request.py
